 export const JOB_TITLE_TO_SPECIALIZATION: Record<string, string> = {
  // Programming & Development
  'Software Developer': 'Programming',
  'Software Engineer': 'Programming',
  'Web Developer': 'Programming',
  'Full Stack Developer': 'Programming',
  'Frontend Developer': 'Programming',
  'Front End Developer': 'Programming',
  'Backend Developer': 'Programming',
  'Back End Developer': 'Programming',
  'Mobile Developer': 'Programming',
  'Application Developer': 'Programming',
  'Game Developer': 'Programming',
  'Game Programmer': 'Programming',
  'DevOps Engineer': 'Programming',
  'QA Engineer': 'Programming',
  'Quality Assurance Engineer': 'Programming',
  'Quality Assurance Tester': 'Programming',
  'QA Tester': 'Programming',
  'Systems Analyst': 'Programming',
  'System Analyst': 'Programming',
  'Systems Developer': 'Programming',
  'Programmer': 'Programming',
  'Junior Developer': 'Programming',
  'Senior Developer': 'Programming',
  'Lead Developer': 'Programming',
  'Technical Lead': 'Programming',
  'Engineering Manager': 'Programming',
  'Software Architect': 'Programming',
  'Solutions Architect': 'Programming',
  'Technical Architect': 'Programming',
  'Integration Developer': 'Programming',
  'API Developer': 'Programming',
  'Database Developer': 'Programming',
  'ETL Developer': 'Programming',
  'BI Developer': 'Programming',
  'Reporting Developer': 'Programming',
  'CRM Developer': 'Programming',
  'ERP Developer': 'Programming',
  'SAP Developer': 'Programming',
  'Salesforce Developer': 'Programming',
  'Shopify Developer': 'Programming',
  'WordPress Developer': 'Programming',
  'PHP Developer': 'Programming',
  'Python Developer': 'Programming',
  'Java Developer': 'Programming',
  'JavaScript Developer': 'Programming',
  'React Developer': 'Programming',
  'Angular Developer': 'Programming',
  'Vue Developer': 'Programming',
  'Node Developer': 'Programming',
  '.NET Developer': 'Programming',
  'C# Developer': 'Programming',
  'C++ Developer': 'Programming',
  'Ruby Developer': 'Programming',
  'Go Developer': 'Programming',
  'Rust Developer': 'Programming',
  'Swift Developer': 'Programming',
  'Kotlin Developer': 'Programming',
  'Flutter Developer': 'Programming',
  'React Native Developer': 'Programming',
  'Mobile App Developer': 'Programming',
  'Android Developer': 'Programming',
  'iOS Developer': 'Programming',
  'AR/VR Developer': 'Programming',
  'Blockchain Developer': 'Programming',
  'Smart Contract Developer': 'Programming',

  // Cybersecurity
  'Security Analyst': 'Cybersecurity',
  'Cybersecurity Analyst': 'Cybersecurity',
  'Information Security Analyst': 'Cybersecurity',
  'Infosec Analyst': 'Cybersecurity',
  'Security Engineer': 'Cybersecurity',
  'Cybersecurity Engineer': 'Cybersecurity',
  'Network Security Engineer': 'Cybersecurity',
  'Security Architect': 'Cybersecurity',
  'Cybersecurity Architect': 'Cybersecurity',
  'Penetration Tester': 'Cybersecurity',
  'Ethical Hacker': 'Cybersecurity',
  'Security Consultant': 'Cybersecurity',
  'Cybersecurity Consultant': 'Cybersecurity',
  'Information Security Manager': 'Cybersecurity',
  'Security Manager': 'Cybersecurity',
  'Security Operations Center Analyst': 'Cybersecurity',
  'SOC Analyst': 'Cybersecurity',
  'Incident Responder': 'Cybersecurity',
  'Security Specialist': 'Cybersecurity',
  'Cybersecurity Specialist': 'Cybersecurity',
  'Security Administrator': 'Cybersecurity',
  'Vulnerability Analyst': 'Cybersecurity',
  'Compliance Analyst': 'Cybersecurity',
  'GRC Analyst': 'Cybersecurity',
  'Security Auditor': 'Cybersecurity',
  'IT Security Analyst': 'Cybersecurity',
  'Cloud Security Engineer': 'Cybersecurity',
  'Application Security Engineer': 'Cybersecurity',
  'Security Researcher': 'Cybersecurity',
  'Cryptographer': 'Cybersecurity',
  'Digital Forensics Analyst': 'Cybersecurity',
  'Forensic Analyst': 'Cybersecurity',
  'Malware Analyst': 'Cybersecurity',
  'Threat Intelligence Analyst': 'Cybersecurity',
  'Security Operations Manager': 'Cybersecurity',
  'CISO': 'Cybersecurity',
  'Chief Information Security Officer': 'Cybersecurity',
  'Data Protection Officer': 'Cybersecurity',
  'Privacy Officer': 'Cybersecurity',

  // Cloud Computing
  'Cloud Engineer': 'Cloud Computing',
  'Cloud Architect': 'Cloud Computing',
  'Cloud Administrator': 'Cloud Computing',
  'AWS Solutions Architect': 'Cloud Computing',
  'AWS Engineer': 'Cloud Computing',
  'AWS Administrator': 'Cloud Computing',
  'Azure Engineer': 'Cloud Computing',
  'Azure Administrator': 'Cloud Computing',
  'Google Cloud Engineer': 'Cloud Computing',
  'GCP Engineer': 'Cloud Computing',
  'Cloud Developer': 'Cloud Computing',
  'Cloud Consultant': 'Cloud Computing',
  'Cloud Security Architect': 'Cloud Computing',
  'Cloud Operations Engineer': 'Cloud Computing',
  'Cloud DevOps Engineer': 'Cloud Computing',
  'Kubernetes Administrator': 'Cloud Computing',
  'Kubernetes Engineer': 'Cloud Computing',
  'Docker Administrator': 'Cloud Computing',
  'Containerization Engineer': 'Cloud Computing',
  'Platform Engineer': 'Cloud Computing',
  'Site Reliability Engineer': 'Cloud Computing',
  'SRE': 'Cloud Computing',
  'Infrastructure Engineer': 'Cloud Computing',
  'Infrastructure Architect': 'Cloud Computing',
  'Hybrid Cloud Engineer': 'Cloud Computing',
  'Multicloud Architect': 'Cloud Computing',
  'Cloud Migration Engineer': 'Cloud Computing',
  'Cloud Solutions Architect': 'Cloud Computing',

  // Data Science & AI
  'Data Scientist': 'Data Science',
  'Data Analyst': 'Data Science',
  'Data Engineer': 'Data Science',
  'Machine Learning Engineer': 'Data Science',
  'AI Engineer': 'Data Science',
  'Artificial Intelligence Engineer': 'Data Science',
  'ML Engineer': 'Data Science',
  'Deep Learning Engineer': 'Data Science',
  'NLP Engineer': 'Data Science',
  'Computer Vision Engineer': 'Data Science',
  'Business Intelligence Analyst': 'Data Science',
  'BI Analyst': 'Data Science',
  
  'Data Architect': 'Data Science',
  'Data Warehouse Architect': 'Data Science',
  'Data Visualization Specialist': 'Data Science',
  'Analytics Manager': 'Data Science',
  'Data Science Manager': 'Data Science',
  'Statistician': 'Data Science',
  'Quantitative Analyst': 'Data Science',
  'Quant Analyst': 'Data Science',
  'Operations Research Analyst': 'Data Science',
  'Predictive Modeler': 'Data Science',
  'Machine Learning Scientist': 'Data Science',
  'AI Researcher': 'Data Science',
  'Data Governance Analyst': 'Data Science',
  'Data Quality Analyst': 'Data Science',
  'Master Data Analyst': 'Data Science',
  'Report Analyst': 'Data Science',
  'Business Analyst': 'Data Science',

  // Multimedia & Design
  'UI/UX Designer': 'Multimedia/Design',
  'UX Designer': 'Multimedia/Design',
  'UI Designer': 'Multimedia/Design',
  'Graphic Designer': 'Multimedia/Design',
  'Visual Designer': 'Multimedia/Design',
  'Web Designer': 'Multimedia/Design',
  'Multimedia Artist': 'Multimedia/Design',
  'Multimedia Designer': 'Multimedia/Design',
  'Video Editor': 'Multimedia/Design',
  'Video Producer': 'Multimedia/Design',
  'Animator': 'Multimedia/Design',
  '3D Animator': 'Multimedia/Design',
  '2D Animator': 'Multimedia/Design',
  'Motion Graphics Artist': 'Multimedia/Design',
  'Motion Designer': 'Multimedia/Design',
  'Art Director': 'Multimedia/Design',
  'Creative Director': 'Multimedia/Design',
  'Creative Designer': 'Multimedia/Design',
  'Brand Designer': 'Multimedia/Design',
  'Brand Identity Designer': 'Multimedia/Design',
  'Logo Designer': 'Multimedia/Design',
  'Illustrator': 'Multimedia/Design',
  'Digital Artist': 'Multimedia/Design',
  'Concept Artist': 'Multimedia/Design',
  'Character Artist': 'Multimedia/Design',
  'Environment Artist': 'Multimedia/Design',
  'Texture Artist': 'Multimedia/Design',
  'Visual Effects Artist': 'Multimedia/Design',
  'VFX Artist': 'Multimedia/Design',
  'Compositor': 'Multimedia/Design',
  'Production Designer': 'Multimedia/Design',
  'Game Designer': 'Multimedia/Design',
  'Game Artist': 'Multimedia/Design',
  'UI Artist': 'Multimedia/Design',
  'UX Researcher': 'Multimedia/Design',
  'Service Designer': 'Multimedia/Design',
  'Interaction Designer': 'Multimedia/Design',
  'Product Designer': 'Multimedia/Design',
  'Packaging Designer': 'Multimedia/Design',
  'Publication Designer': 'Multimedia/Design',
  'Print Designer': 'Multimedia/Design',
  'Layout Artist': 'Multimedia/Design',
  'Photographer': 'Multimedia/Design',
  'Videographer': 'Multimedia/Design',
  'Content Creator': 'Multimedia/Design',
  'Social Media Designer': 'Multimedia/Design',
  'Frontend Designer': 'Multimedia/Design',

  // Networking & Infrastructure
  'Network Administrator': 'Networking',
  'Network Engineer': 'Networking',
  'Network Architect': 'Networking',
  'Network Analyst': 'Networking',
  'System Administrator': 'Networking',
  'Systems Administrator': 'Networking',
  'System Engineer': 'Networking',
  'Systems Engineer': 'Networking',
  'IT Administrator': 'Networking',
  'IT Support Specialist': 'Networking',
  'IT Support Engineer': 'Networking',
  'IT Specialist': 'Networking',
  'Infrastructure Administrator': 'Networking',
  
  'Infrastructure Manager': 'Networking',
  'Network Manager': 'Networking',
  'IT Manager': 'Networking',
  'Technical Support Engineer': 'Networking',
  'Help Desk Analyst': 'Networking',
  'IT Help Desk': 'Networking',
  'Desktop Support': 'Networking',
  'Network Security Administrator': 'Networking',
  'Voice Network Engineer': 'Networking',
  'Telecom Engineer': 'Networking',
  'Telecommunications Engineer': 'Networking',
  'Wireless Engineer': 'Networking',
  'Wireless Network Engineer': 'Networking',
  'Cisco Network Engineer': 'Networking',
  'Cisco Administrator': 'Networking',
  'Systems Architect': 'Networking',
  'Enterprise Architect': 'Networking',
  'Server Administrator': 'Networking',
  'Database Administrator': 'Networking',
  'DBA': 'Networking',
  'Storage Administrator': 'Networking',
  'Backup Administrator': 'Networking',
  'Disaster Recovery Specialist': 'Networking',
  'IT Operations Manager': 'Networking',
  'Technology Manager': 'Networking',
  'Service Desk Manager': 'Networking',
  'IT Director': 'Networking',

  // Hospitality - Hotel Operations
  'Hotel Manager': 'Hotel Operations',
  'Hotel General Manager': 'Hotel Operations',
  'Hotel Operations Manager': 'Hotel Operations',
  'Front Office Manager': 'Hotel Operations',
  'Front Desk Manager': 'Hotel Operations',
  'Front Desk Supervisor': 'Hotel Operations',
  'Guest Services Manager': 'Hotel Operations',
  'Guest Relations Manager': 'Hotel Operations',
  'Guest Services Agent': 'Hotel Operations',
  'Front Desk Agent': 'Hotel Operations',
  'Hotel Receptionist': 'Hotel Operations',
  'Concierge': 'Hotel Operations',
  'Reservations Manager': 'Hotel Operations',
  'Revenue Manager': 'Hotel Operations',
  'Revenue Analyst': 'Hotel Operations',
  'Yield Manager': 'Hotel Operations',
  'Sales Manager': 'Hotel Operations',
  'Sales Executive': 'Hotel Operations',
  'Marketing Manager': 'Hotel Operations',
  'Housekeeping Manager': 'Hotel Operations',
  'Executive Housekeeper': 'Hotel Operations',
  'Housekeeping Supervisor': 'Hotel Operations',
  'Laundry Manager': 'Hotel Operations',
  'Maintenance Manager': 'Hotel Operations',
  'Facilities Manager': 'Hotel Operations',
   
  'Hotel Director': 'Hotel Operations',
  'Resort Manager': 'Hotel Operations',
  'Resort General Manager': 'Hotel Operations',
  'Casino Manager': 'Hotel Operations',
  'Spa Manager': 'Hotel Operations',
  'Wellness Manager': 'Hotel Operations',
  'Club Manager': 'Hotel Operations',
  'Membership Manager': 'Hotel Operations',

  // Hospitality - Events Management
  'Event Coordinator': 'Events Management',
  'Event Manager': 'Events Management',
  'Events Manager': 'Events Management',
  'Wedding Coordinator': 'Events Management',
  'Wedding Planner': 'Events Management',
  'Events Planner': 'Events Management',
  'Conference Coordinator': 'Events Management',
  'Conference Manager': 'Events Management',
  'Convention Manager': 'Events Management',
  'Exhibition Coordinator': 'Events Management',
  'Trade Show Manager': 'Events Management',
  'Corporate Event Planner': 'Events Management',
  'Corporate Events Manager': 'Events Management',
  'Social Event Coordinator': 'Events Management',
  'Community Event Coordinator': 'Events Management',
  'Fundraising Coordinator': 'Events Management',
  'Nonprofit Events Manager': 'Events Management',
  'Festival Coordinator': 'Events Management',
  'Cultural Events Manager': 'Events Management',
  'Sports Events Coordinator': 'Events Management',
  'Entertainment Manager': 'Events Management',
  'Event Production Manager': 'Events Management',
  'Production Coordinator': 'Events Management',
  'Venue Manager': 'Events Management',
  'Event Marketing Manager': 'Events Management',
  'Event Operations Manager': 'Events Management',
  'Event Director': 'Events Management',

  // Hospitality - Food & Beverage
  'Food and Beverage Manager': 'Food and Beverage',
  'F&B Manager': 'Food and Beverage',
  'Food and Beverage Supervisor': 'Food and Beverage',
  'Restaurant Manager': 'Food and Beverage',
  'Assistant Restaurant Manager': 'Food and Beverage',
  'Catering Manager': 'Food and Beverage',
  'Catering Coordinator': 'Food and Beverage',
  'Banquet Manager': 'Food and Beverage',
  'Banquet Coordinator': 'Food and Beverage',
  'Bar Manager': 'Food and Beverage',
  'Bartender': 'Food and Beverage',
  'Head Bartender': 'Food and Beverage',
  'Beverage Manager': 'Food and Beverage',
  'Sommelier': 'Food and Beverage',
  'Wine Manager': 'Food and Beverage',
  'Executive Chef': 'Food and Beverage',
  'Head Chef': 'Food and Beverage',
  'Sous Chef': 'Food and Beverage',
  'Line Cook': 'Food and Beverage',
  'Pastry Chef': 'Food and Beverage',
  'Baker': 'Food and Beverage',
  'Kitchen Manager': 'Food and Beverage',
  'Food Service Manager': 'Food and Beverage',
  'Culinary Director': 'Food and Beverage',
  'Menu Planner': 'Food and Beverage',
  'Food Safety Manager': 'Food and Beverage',
  'Dietitian': 'Food and Beverage',
  'Nutritionist': 'Food and Beverage',
  'Food Quality Specialist': 'Food and Beverage',

  // Hospitality - Tourism Management
  'Tourism Officer': 'Tourism Management',
  'Tourism Manager': 'Tourism Management',
  'Tourism Development Officer': 'Tourism Management',
  'Tourist Information Officer': 'Tourism Management',
  'Tour Guide': 'Tourism Management',
  'Tour Coordinator': 'Tourism Management',
  'Tour Operator': 'Tourism Management',
  'Travel Consultant': 'Tourism Management',
  'Travel Agent': 'Tourism Management',
  'Travel Manager': 'Tourism Management',
  'Travel Agency Manager': 'Tourism Management',
  'Destination Manager': 'Tourism Management',
  'Destination Marketing Manager': 'Tourism Management',
  'Visitor Experience Manager': 'Tourism Management',
  'Heritage Manager': 'Tourism Management',
  'Cultural Heritage Officer': 'Tourism Management',
  'Museum Manager': 'Tourism Management',
  'Theme Park Manager': 'Tourism Management',
  'Attractions Manager': 'Tourism Management',
  'Adventure Tourism Manager': 'Tourism Management',
  'Eco-Tourism Manager': 'Tourism Management',
  'Community Tourism Coordinator': 'Tourism Management',
  'Tourism Researcher': 'Tourism Management',
  'Tourism Policy Analyst': 'Tourism Management',

  // Business - Marketing
  
  'Marketing Specialist': 'Marketing',
  'Marketing Coordinator': 'Marketing',
  'Digital Marketing Specialist': 'Marketing',
  'Digital Marketing Manager': 'Marketing',
  'Social Media Specialist': 'Marketing',
  'Social Media Manager': 'Marketing',
  'Content Marketing Manager': 'Marketing',
  'Content Strategist': 'Marketing',
  'SEO Specialist': 'Marketing',
  'SEM Specialist': 'Marketing',
  'PPC Specialist': 'Marketing',
  'Paid Media Specialist': 'Marketing',
  'Marketing Analytics Manager': 'Marketing',
  'Marketing Research Analyst': 'Marketing',
  'Market Research Analyst': 'Marketing',
  'Brand Manager': 'Marketing',
  'Product Marketing Manager': 'Marketing',
  'Product Manager': 'Marketing',
  'Campaign Manager': 'Marketing',
  'Advertising Manager': 'Marketing',
  'Media Planner': 'Marketing',
  'Public Relations Manager': 'Marketing',
  'PR Specialist': 'Marketing',
  'Communications Manager': 'Marketing',
  'Corporate Communications Manager': 'Marketing',
  'Internal Communications Specialist': 'Marketing',
  'Event Marketing Specialist': 'Marketing',
  'Influencer Marketing Manager': 'Marketing',
  'Affiliate Marketing Manager': 'Marketing',
  'Email Marketing Specialist': 'Marketing',
  'Growth Marketing Manager': 'Marketing',
  'Demand Generation Manager': 'Marketing',
  'Field Marketing Manager': 'Marketing',
  'Trade Marketing Manager': 'Marketing',
  'Marketing Director': 'Marketing',
  'Chief Marketing Officer': 'Marketing',
  'CMO': 'Marketing',

  // Business - Finance
  'Financial Analyst': 'Finance',
  'Finance Analyst': 'Finance',
  'Financial Advisor': 'Finance',
  'Investment Analyst': 'Finance',
  'Investment Banker': 'Finance',
  'Wealth Manager': 'Finance',
  'Financial Planner': 'Finance',
  'Accountant': 'Finance',
  'CPA': 'Finance',
  'Certified Public Accountant': 'Finance',
  'Senior Accountant': 'Finance',
  'Staff Accountant': 'Finance',
  'Accounting Manager': 'Finance',
  'Finance Manager': 'Finance',
  'Financial Controller': 'Finance',
  'Chief Financial Officer': 'Finance',
  'CFO': 'Finance',
  'Internal Auditor': 'Finance',
  'External Auditor': 'Finance',
  'Audit Manager': 'Finance',
  'Tax Consultant': 'Finance',
  'Tax Analyst': 'Finance',
  'Tax Manager': 'Finance',
  'Risk Analyst': 'Finance',
  'Risk Manager': 'Finance',
  'Credit Analyst': 'Finance',
  'Loan Officer': 'Finance',
  'Portfolio Manager': 'Finance',
  'Finance Director': 'Finance',
  'Treasury Analyst': 'Finance',
  'Treasury Manager': 'Finance',
  'Budget Analyst': 'Finance',
  'Cost Accountant': 'Finance',
  'Forensic Accountant': 'Finance',

  // Business - Human Resources
  'HR Manager': 'Human Resources',
  'Human Resources Manager': 'Human Resources',
  'Human Resources Specialist': 'Human Resources',
  'HR Specialist': 'Human Resources',
  'HR Coordinator': 'Human Resources',
  'HR Business Partner': 'Human Resources',
  'HR Generalist': 'Human Resources',
  'Recruitment Specialist': 'Human Resources',
  'Recruiter': 'Human Resources',
  'Talent Acquisition Specialist': 'Human Resources',
  'Talent Acquisition Manager': 'Human Resources',
  'Talent Management Specialist': 'Human Resources',
  'Training and Development Manager': 'Human Resources',
  'Training Coordinator': 'Human Resources',
  'Organizational Development Specialist': 'Human Resources',
  'OD Specialist': 'Human Resources',
  'Compensation Analyst': 'Human Resources',
  'Benefits Analyst': 'Human Resources',
  'Compensation and Benefits Manager': 'Human Resources',
  'Payroll Specialist': 'Human Resources',
  'Payroll Manager': 'Human Resources',
  'Employee Relations Manager': 'Human Resources',
  'Labor Relations Specialist': 'Human Resources',
  'HR Director': 'Human Resources',
  'Chief Human Resources Officer': 'Human Resources',
  'CHRO': 'Human Resources',
  'HR Consultant': 'Human Resources',
  'HRIS Analyst': 'Human Resources',
  'HR Data Analyst': 'Human Resources',
  'Diversity and Inclusion Manager': 'Human Resources',
  'DEI Specialist': 'Human Resources',

  // Business - Operations Management
  'Operations Manager': 'Operations Management',
  'Operations Supervisor': 'Operations Management',
  'Operations Analyst': 'Operations Management',
  'Operations Coordinator': 'Operations Management',
  'Operations Director': 'Operations Management',
  'Supply Chain Manager': 'Operations Management',
  'Supply Chain Analyst': 'Operations Management',
  'Logistics Manager': 'Operations Management',
  'Logistics Coordinator': 'Operations Management',
  'Warehouse Manager': 'Operations Management',
  'Warehouse Supervisor': 'Operations Management',
  'Procurement Manager': 'Operations Management',
  'Purchasing Manager': 'Operations Management',
  'Purchasing Agent': 'Operations Management',
  'Inventory Manager': 'Operations Management',
  'Inventory Control Specialist': 'Operations Management',
  'Quality Assurance Manager': 'Operations Management',
  'Quality Control Manager': 'Operations Management',
  'Quality Engineer': 'Operations Management',
  'Project Manager': 'Operations Management',
  'Project Coordinator': 'Operations Management',
  'Program Manager': 'Operations Management',
  'Production Manager': 'Operations Management',
  'Production Supervisor': 'Operations Management',
  'Plant Manager': 'Operations Management',
  'Facility Manager': 'Operations Management',
  'Chief Operations Officer': 'Operations Management',
  'COO': 'Operations Management',
  'Business Operations Manager': 'Operations Management',

  // Business - Entrepreneurship
  'Entrepreneur': 'Entrepreneurship',
  'Founder': 'Entrepreneurship',
  'Co-Founder': 'Entrepreneurship',
  'CEO': 'Entrepreneurship',
  'Chief Executive Officer': 'Entrepreneurship',
  'Managing Director': 'Entrepreneurship',
  'Managing Partner': 'Entrepreneurship',
  'Owner': 'Entrepreneurship',
  'Business Owner': 'Entrepreneurship',
  'Small Business Owner': 'Entrepreneurship',
  'Startup Founder': 'Entrepreneurship',
  'Startup CEO': 'Entrepreneurship',
  'Director': 'Entrepreneurship',
  'Vice President': 'Entrepreneurship',
  'President': 'Entrepreneurship',
  'Board Member': 'Entrepreneurship',
  'Chairman': 'Entrepreneurship',
  'Venture Capitalist': 'Entrepreneurship',
  'Angel Investor': 'Entrepreneurship',
  'Business Consultant': 'Entrepreneurship',
  'Management Consultant': 'Entrepreneurship',

  // Education
  'Teacher': 'Education',
  'Educator': 'Education',
  'Instructor': 'Education',
  'Professor': 'Education',
  'Assistant Professor': 'Education',
  'Associate Professor': 'Education',
  'Adjunct Professor': 'Education',
  'School Teacher': 'Education',
  'Elementary Teacher': 'Education',
  'High School Teacher': 'Education',
  'College Instructor': 'Education',
  'University Lecturer': 'Education',
  'School Administrator': 'Education',
  'Principal': 'Education',
  'Vice Principal': 'Education',
  'Dean': 'Education',
  'Academic Dean': 'Education',
  'Department Head': 'Education',
  'Program Coordinator': 'Education',
  'Curriculum Developer': 'Education',
  'Instructional Designer': 'Education',
  'Educational Consultant': 'Education',
  'Academic Advisor': 'Education',
  'School Counselor': 'Education',
  'Guidance Counselor': 'Education',
  'Education Specialist': 'Education',
  'Training Manager': 'Education',
  'Corporate Trainer': 'Education',
  'Learning and Development Manager': 'Education',
  'L&D Manager': 'Education',
  'Instructional Coordinator': 'Education',
  'Librarian': 'Education',
  'Media Specialist': 'Education',

  // Engineering
  'Civil Engineer': 'Engineering',
  'Mechanical Engineer': 'Engineering',
  'Electrical Engineer': 'Engineering',
  'Electronic Engineer': 'Engineering',
  'Industrial Engineer': 'Engineering',
  'Chemical Engineer': 'Engineering',
  'Environmental Engineer': 'Engineering',
  'Structural Engineer': 'Engineering',
  'Geotechnical Engineer': 'Engineering',
  'Transportation Engineer': 'Engineering',
  'Aerospace Engineer': 'Engineering',
  'Automotive Engineer': 'Engineering',
  'Biomedical Engineer': 'Engineering',
  'Materials Engineer': 'Engineering',
  'Petroleum Engineer': 'Engineering',
  'Mining Engineer': 'Engineering',
  'Nuclear Engineer': 'Engineering',
  'Robotics Engineer': 'Engineering',
  'CAD Designer': 'Engineering',
  'Draftsman': 'Engineering',
  'Architect': 'Engineering',
  'Architectural Designer': 'Engineering',
  'Urban Planner': 'Engineering',
  'Quantity Surveyor': 'Engineering',
  'Project Engineer': 'Engineering',
  'Field Engineer': 'Engineering',
  'Maintenance Engineer': 'Engineering',
  'Facilities Engineer': 'Engineering',

  // Healthcare
  'Doctor': 'Healthcare',
  'Physician': 'Healthcare',
  'Nurse': 'Healthcare',
  'Registered Nurse': 'Healthcare',
  'Nursing Manager': 'Healthcare',
  'Nursing Supervisor': 'Healthcare',
  'Medical Specialist': 'Healthcare',
  'Surgeon': 'Healthcare',
  'Dentist': 'Healthcare',
  'Pharmacist': 'Healthcare',
  'Clinical Pharmacist': 'Healthcare',
  'Radiologist': 'Healthcare',
  'Pathologist': 'Healthcare',
  'Medical Technologist': 'Healthcare',
  'Medical Lab Scientist': 'Healthcare',
  'Physical Therapist': 'Healthcare',
  'Occupational Therapist': 'Healthcare',
  'Speech Therapist': 'Healthcare',
  'Respiratory Therapist': 'Healthcare',
  'Medical Researcher': 'Healthcare',
  'Public Health Officer': 'Healthcare',
  'Community Health Worker': 'Healthcare',
  'Health Educator': 'Healthcare',
  'Epidemiologist': 'Healthcare',
  'Biostatistician': 'Healthcare',
  'Healthcare Administrator': 'Healthcare',
  'Hospital Administrator': 'Healthcare',
  'Health Information Manager': 'Healthcare',
  'Medical Billing Specialist': 'Healthcare',
  'Claims Analyst': 'Healthcare',
  'Medical Coder': 'Healthcare',
  'Clinical Data Analyst': 'Healthcare',
  'Pharmaceutical Sales Representative': 'Healthcare',

  // Legal
  'Lawyer': 'Legal',
  'Attorney': 'Legal',
  'Legal Counsel': 'Legal',
  'Corporate Lawyer': 'Legal',
  'Litigation Lawyer': 'Legal',
  'Judge': 'Legal',
  'Prosecutor': 'Legal',
  'Public Defender': 'Legal',
  'Legal Assistant': 'Legal',
  'Paralegal': 'Legal',
  'Legal Analyst': 'Legal',
  'Court Clerk': 'Legal',
  'Legislative Assistant': 'Legal',
  'Policy Analyst': 'Legal',
  'Government Administrator': 'Legal',
  'Civil Service Officer': 'Legal',
  'Foreign Service Officer': 'Legal',
  'Diplomat': 'Legal',

  // Other
  'Freelancer': 'Other',
  'Freelance': 'Other',
  'Consultant': 'Other',
  'Self-Employed': 'Other',
  'Student': 'Other',
  'Full-time Student': 'Other',
  'Part-time Student': 'Other',
  'Unemployed': 'Other',
  'Retired': 'Other',
  'Homemaker': 'Other',
  'Stay-at-home Parent': 'Other',
  'Volunteer': 'Other',
  'Intern': 'Other',
  'Trainee': 'Other',
  'Apprentice': 'Other',
  'Junior': 'Other',
  'Senior': 'Other',
  'Executive': 'Other',
  'Manager': 'Other',
  'Supervisor': 'Other',
  'Team Lead': 'Other',
  'Team Leader': 'Other',
  'Coordinator': 'Other',
  'Administrator': 'Other',
  'Assistant': 'Other',
  'Associate': 'Other',
  'Specialist': 'Other',
  'Analyst': 'Other',
  'Technician': 'Other',
  'Operator': 'Other',
  'Worker': 'Other',
};

export function getSpecializationFromJobTitle(jobTitle: string): string {
  if (!jobTitle) return 'Unspecified';

  const normalizedTitle = jobTitle.trim();

  // Exact match
  if (JOB_TITLE_TO_SPECIALIZATION[normalizedTitle]) {
    return JOB_TITLE_TO_SPECIALIZATION[normalizedTitle];
  }

  // Case-insensitive match
  const lowerTitle = normalizedTitle.toLowerCase();
  const exactMatchKey = Object.keys(JOB_TITLE_TO_SPECIALIZATION).find(
    key => key.toLowerCase() === lowerTitle
  );
  if (exactMatchKey) {
    return JOB_TITLE_TO_SPECIALIZATION[exactMatchKey];
  }

  // Keyword matches
  const keywordGroups = [
    { patterns: ['developer', 'programmer', 'software', 'application', 'coding', 'programming', 'full stack', 'frontend', 'backend', 'react', 'angular', 'vue', 'node', 'php', 'python', 'java', 'javascript', 'c#', 'c++', 'ruby', 'go', 'rust', 'swift', 'kotlin', 'flutter'], result: 'Programming' },
    { patterns: ['security', 'cyber', 'ethical hacker', 'penetration', 'vulnerability', 'compliance', 'auditor', 'forensic', 'malware', 'threat', 'incident', 'ciso'], result: 'Cybersecurity' },
    { patterns: ['cloud', 'aws', 'azure', 'gcp', 'kubernetes', 'docker', 'container', 'platform', 'devops', 'sre', 'infrastructure'], result: 'Cloud Computing' },
    { patterns: ['data scientist', 'data analyst', 'data engineer', 'machine learning', 'ai', 'artificial intelligence', 'business intelligence', 'bi', 'analytics', 'statistician'], result: 'Data Science' },
    { patterns: ['designer', 'animator', 'artist', 'creative', 'multimedia', 'video', 'motion', 'ui', 'ux', 'graphic', 'illustrator', 'photographer', 'content creator'], result: 'Multimedia/Design' },
    { patterns: ['network', 'infrastructure', 'system admin', 'sysadmin', 'it support', 'help desk', 'desktop', 'server', 'storage', 'backup', 'telecom', 'database admin', 'dba'], result: 'Networking' },
    { patterns: ['hotel', 'resort', 'front desk', 'concierge', 'guest', 'housekeeping', 'reception'], result: 'Hotel Operations' },
    { patterns: ['event', 'wedding', 'conference', 'convention', 'exhibition', 'trade show'], result: 'Events Management' },
    { patterns: ['restaurant', 'catering', 'banquet', 'bar', 'beverage', 'chef', 'cook', 'culinary', 'food'], result: 'Food and Beverage' },
    { patterns: ['tour', 'travel', 'tourism', 'destination', 'tourist'], result: 'Tourism Management' },
    { patterns: ['marketing', 'brand', 'advertising', 'pr', 'social media', 'seo', 'sem', 'ppc', 'content'], result: 'Marketing' },
    { patterns: ['finance', 'accountant', 'accounting', 'audit', 'tax', 'risk', 'investment', 'wealth', 'treasury'], result: 'Finance' },
    { patterns: ['hr', 'human resources', 'recruitment', 'talent', 'training', 'compensation', 'benefits', 'payroll'], result: 'Human Resources' },
    { patterns: ['operations', 'supply chain', 'logistics', 'warehouse', 'procurement', 'inventory', 'quality', 'production'], result: 'Operations Management' },
    { patterns: ['entrepreneur', 'founder', 'ceo', 'president', 'owner', 'startup'], result: 'Entrepreneurship' },
    { patterns: ['teacher', 'professor', 'instructor', 'educator', 'lecturer', 'principal', 'dean', 'curriculum', 'academic'], result: 'Education' },
    { patterns: ['engineer', 'architect', 'draftsman', 'surveyor'], result: 'Engineering' },
    { patterns: ['doctor', 'physician', 'nurse', 'dentist', 'pharmacist', 'therapist', 'medical', 'clinical', 'health'], result: 'Healthcare' },
    { patterns: ['lawyer', 'attorney', 'legal', 'judge', 'prosecutor', 'paralegal'], result: 'Legal' },
  ];

  for (const group of keywordGroups) {
    for (const pattern of group.patterns) {
      if (lowerTitle.includes(pattern)) {
        return group.result;
      }
    }
  }

  return 'Other';
}